from __future__ import annotations

"""
WatchdogService — auto-recovery for Control Center and Pi-hole.

The watchdog script and systemd unit are generated and installed entirely from
Python (same pattern as CoreServiceManager), so there are no separate shell
scripts or service files that need to be manually copied.

Usage (automatic — called by bootstrap-host and self-heal):
    watchdog = WatchdogService(settings)
    watchdog.install_and_enable()

Or via CLI:
    homelabctl install-watchdog
"""

import subprocess
import tempfile
from pathlib import Path

from homelab_os.core.config import Settings


class WatchdogService:
    SERVICE_NAME = "homelab-watchdog.service"
    SCRIPT_PATH  = Path("/usr/local/bin/homelab-watchdog")

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    # ── Generated content ──────────────────────────────────────────────────────

    def _script_content(self) -> str:
        pihole_dir  = self.settings.runtime_installed_plugins_dir / "pihole" / "docker"
        logs_dir    = self.settings.logs_dir
        cc_service  = "homelab-os-core.service"
        return f"""\
#!/usr/bin/env bash
# homelab-watchdog — auto-generated by WatchdogService (do not edit manually).
# Monitors Control Center and Pi-hole; restarts either if it goes down.
# Managed by: {self.SERVICE_NAME}

set -euo pipefail

LOG_FILE="{logs_dir}/watchdog.log"
PIHOLE_DIR="{pihole_dir}"
CHECK_INTERVAL=60

log() {{
    echo "$(date '+%Y-%m-%dT%H:%M:%S') $*" >> "$LOG_FILE" 2>/dev/null || true
    logger -t homelab-watchdog "$*" 2>/dev/null || true
}}

# ── Control Center ────────────────────────────────────────────────────────────
check_control_center() {{
    if ! systemctl is-active --quiet {cc_service}; then
        log "WARN: {cc_service} is not active — restarting"
        if systemctl restart {cc_service} 2>/dev/null; then
            log "OK: {cc_service} restarted"
        else
            log "ERROR: failed to restart {cc_service}"
        fi
    fi
}}

# ── Pi-hole ───────────────────────────────────────────────────────────────────
check_pihole() {{
    if ! docker inspect pihole &>/dev/null; then
        log "WARN: pihole container not found — running docker compose up"
        if [[ -d "$PIHOLE_DIR" ]]; then
            if docker compose -p pihole -f "$PIHOLE_DIR/docker-compose.yml" up -d --remove-orphans 2>/dev/null; then
                log "OK: pihole container started via compose"
            else
                log "ERROR: docker compose up failed for pihole"
            fi
        else
            log "ERROR: $PIHOLE_DIR not found — reinstall pihole plugin from Control Center"
        fi
        return
    fi

    local state
    state=$(docker inspect -f '{{{{.State.Status}}}}' pihole 2>/dev/null || echo "unknown")

    case "$state" in
        running)
            if ! curl -sf --max-time 5 http://127.0.0.1:8080/admin/ -o /dev/null 2>/dev/null; then
                log "WARN: pihole running but admin UI not responding — restarting container"
                if docker restart pihole 2>/dev/null; then
                    log "OK: pihole restarted"
                else
                    log "ERROR: docker restart pihole failed"
                fi
            fi
            ;;
        exited|dead|created)
            log "WARN: pihole container is '$state' — starting"
            if docker start pihole 2>/dev/null; then
                log "OK: pihole started"
            else
                log "ERROR: docker start pihole failed"
            fi
            ;;
        restarting)
            log "INFO: pihole is restarting — skipping intervention"
            ;;
        *)
            log "WARN: pihole in unexpected state '$state'"
            ;;
    esac
}}

# ── Main loop ─────────────────────────────────────────────────────────────────
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true
log "homelab-watchdog started (interval: ${{CHECK_INTERVAL}}s)"

while true; do
    check_control_center
    check_pihole
    sleep "$CHECK_INTERVAL"
done
"""

    def _service_unit_content(self) -> str:
        return f"""\
[Unit]
Description=Homelab OS Watchdog — auto-recovery for Control Center and Pi-hole
After=network-online.target docker.service
Wants=network-online.target docker.service

[Service]
Type=simple
ExecStartPre=/bin/mkdir -p {self.settings.logs_dir}
ExecStart={self.SCRIPT_PATH}
Restart=always
RestartSec=10s
User=root
StandardOutput=journal
StandardError=journal
SyslogIdentifier=homelab-watchdog

[Install]
WantedBy=multi-user.target
"""

    # ── Internal helpers ───────────────────────────────────────────────────────

    def _run(self, cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
        return subprocess.run(cmd, check=check, capture_output=True, text=True)

    def _write_via_sudo(self, content: str, dest: Path, mode: str | None = None) -> None:
        """Write content to a system path using a temp file + sudo cp."""
        with tempfile.NamedTemporaryFile("w", delete=False, encoding="utf-8", suffix=".tmp") as tmp:
            tmp.write(content)
            tmp_path = Path(tmp.name)
        try:
            self._run(["sudo", "cp", str(tmp_path), str(dest)], check=True)
            if mode:
                self._run(["sudo", "chmod", mode, str(dest)], check=True)
        finally:
            tmp_path.unlink(missing_ok=True)

    # ── Public API ─────────────────────────────────────────────────────────────

    def status(self) -> str:
        result = self._run(["systemctl", "is-active", self.SERVICE_NAME], check=False)
        return result.stdout.strip() or "unknown"

    def is_enabled(self) -> bool:
        result = self._run(["systemctl", "is-enabled", self.SERVICE_NAME], check=False)
        return result.returncode == 0

    def install_script(self) -> None:
        """Install the watchdog bash script to /usr/local/bin/homelab-watchdog."""
        self._run(["sudo", "mkdir", "-p", str(self.SCRIPT_PATH.parent)], check=True)
        self._write_via_sudo(self._script_content(), self.SCRIPT_PATH, mode="755")

    def install_service(self) -> None:
        """Install the systemd unit file to /etc/systemd/system/."""
        dest = Path(f"/etc/systemd/system/{self.SERVICE_NAME}")
        self._run(["sudo", "mkdir", "-p", "/etc/systemd/system"], check=True)
        self._write_via_sudo(self._service_unit_content(), dest, mode="644")
        self._run(["sudo", "systemctl", "daemon-reload"], check=True)

    def enable_and_start(self) -> None:
        """Enable the watchdog service to start on boot and start it now."""
        self._run(["sudo", "systemctl", "enable", self.SERVICE_NAME], check=True)
        self._run(["sudo", "systemctl", "restart", self.SERVICE_NAME], check=True)

    def install_and_enable(self) -> None:
        """Full idempotent install: script → unit → enable → start."""
        self.install_script()
        self.install_service()
        self.enable_and_start()

    def reinstall(self) -> None:
        """Re-generate and reinstall (e.g. after settings change)."""
        self.install_and_enable()
