services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:4533:4533"
    environment:
      ND_SCANSCHEDULE: 5m
      ND_LOGLEVEL: info
      ND_BASEURL: /
      ND_SESSIONTIMEOUT: 720h
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      ND_SHAREURL: https://pi-nas.taild4713b.ts.net:8445
    volumes:
      - ./data:/data
      - /mnt/nas/media/music:/music:ro
